services:
  drone:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      BOT_UN: $BOT_UN
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
